# Generated by Django 4.2.4 on 2023-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_nv', models.CharField(max_length=50, verbose_name='Название')),
                ('anons_nv', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text_nv', models.TextField(verbose_name='Статья')),
                ('date_nv', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
